In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [3]:
tf.__version__, keras.__version__

('2.17.0', '3.4.1')

In [4]:
Variable = tf.Variable([3,3])   
type(Variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [5]:
if tf.test.is_gpu_available():
    print('GPU')
else:
    print('CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU


In [6]:
Samrat = tf.constant([100,12])
Samrat

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100,  12])>

In [7]:
Samrat.numpy()

array([100,  12])

In [8]:
Samrat.dtype

tf.int32

In [9]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
tf.random.normal(shape = (2,2), mean = 0, stddev = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.0804307 , -0.7166056 ],
       [ 0.07900439,  0.39669427]], dtype=float32)>

In [11]:
tf.random.uniform(shape = (2,2), minval = 1, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [5, 2]])>

In [12]:
X = tf.constant(4, shape = (3,3), dtype = tf.float32)
print(X)

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(3, 3), dtype=float32)


In [13]:
tf.ones([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [14]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [15]:
tf.range(start = 20, limit= 100, delta = 5)

<tf.Tensor: shape=(16,), dtype=int32, numpy=array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])>

In [19]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
x_train = x_train.reshape(-1, 28*28).astype('float32') / 255.0
x_test = x_test.reshape(-1, 28*28).astype('float32') / 255.0
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)
(60000, 784)
(60000,)


In [33]:
model = keras.Sequential(
    [
        keras.Input(shape = (28*28,)),
        layers.Dense(512, activation = 'relu'),
        layers.Dense(256, activation = 'relu'),
        layers.Dense(10)
    ]
)
print(model.summary())

import sys
sys.exit

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

None


<function sys.exit(status=None, /)>

In [28]:
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits= True),
    optimizer = keras.optimizers.Adam(learning_rate=0.001),
    metrics = ['accuracy']
)

In [29]:
model.fit(x_train, y_train, batch_size = 32, epochs = 5, verbose = 2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)

Epoch 1/5
1875/1875 - 8s - 4ms/step - accuracy: 0.9441 - loss: 0.1865
Epoch 2/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9748 - loss: 0.0788
Epoch 3/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9835 - loss: 0.0523
Epoch 4/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9862 - loss: 0.0411
Epoch 5/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9888 - loss: 0.0332
313/313 - 1s - 2ms/step - accuracy: 0.9810 - loss: 0.0714


[0.07143579423427582, 0.9810000061988831]