In [1]:
import tensorflow as tf
import keras 

In [2]:
tf.__version__, keras.__version__

('2.17.0', '3.4.1')

In [3]:
Variable = tf.Variable([3,3])   
type(Variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [4]:
if tf.test.is_gpu_available():
    print('GPU')
else:
    print('CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU


In [5]:
Samrat = tf.constant([100,12])
Samrat

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100,  12])>

In [6]:
Samrat.numpy()

array([100,  12])

In [7]:
Samrat.dtype

tf.int32

In [8]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
tf.random.normal(shape = (2,2), mean = 0, stddev = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5481135 ,  0.12777202],
       [ 0.47599265, -1.225415  ]], dtype=float32)>

In [10]:
tf.random.uniform(shape = (2,2), minval = 1, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 1],
       [6, 8]])>

In [13]:
X = tf.constant(4, shape = (3,3), dtype = tf.float32)
print(X)

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(3, 3), dtype=float32)


In [15]:
tf.ones([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [19]:
tf.range(start = 20, limit= 100, delta = 5)

<tf.Tensor: shape=(16,), dtype=int32, numpy=array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])>